repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
    name: Checking EOF
    exclude: (assets|thirdparty)
  - id: trailing-whitespace
    name: Checking trailing whitespace
    exclude: (assets|thirdparty)
  - id: check-merge-conflict
    name: Checking merge conflicts
    exclude: (assets|thirdparty)
